name: build Community Shaders and addons

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

env:
  VCPKG_COMMIT_ID: 34742e119fb2aae42f10c03a98e475eb1934f7c9

jobs:
  compile:
    name: build plugin and addons
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: 'true'

        - uses: ilammy/msvc-dev-cmd@v1.10.0

        - uses: lukka/run-vcpkg@v11
          with:
              vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

        - name: cmake configure
          run: cmake -S . --preset=ALL --check-stamp-file "build\CMakeFiles\generate.stamp"

        - name: cmake build
          run: cmake --build build --config Release

        - name: create a tagged release and upload the archive
          uses: ncipollo/release-action@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            name: Community Shaders ${{ github.ref_name }}
            draft: true
            tag: ${{ github.ref_name }}
            artifacts: "${{ github.workspace }}/dist/*.7z"
